CC		= g++
CFLAGS		= -g -c -Wall
LDFLAGS		= 
SOURCEDIR = ./src/
SOURCES		= $(SOURCEDIR)client.cpp $(SOURCEDIR)tcpstream.cpp $(SOURCEDIR)tcpconnector.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)

