CC		= g++
CFLAGS		= -g -c -Wall 
LDFLAGS		= 
SOURCEDIR = ./src/
SOURCEOBJ = ./obj/
SOURCES		= $(SOURCEDIR)server.cpp $(SOURCEDIR)tcpstream.cpp $(SOURCEDIR)tcpacceptor.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= server

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)


